default:
  properties:
    proxy.enabled: false
    allure.report: true
    allure.create.enviroment: true
  contexts: [dev, chrome]

contexts:
  chrome:
    webdriver.cap.browserName: chrome
    webdriver.type: customChrome
    webdriver.reusable: true
  firefox:
    webdriver.cap.browserName: firefox
  dev:
    author.url: http://localhost:4505
    author.ip: http://127.0.0.1:4505
    author.login: admin
    author.password: admin
    publish.url: http://localhost:4506
    publish.ip: http://127.0.0.1:4506
    login.token.name: login-token
  prod:
    author.url: http://localhost:4505
    author.ip: http://127.0.0.1:4505
    author.login: admin
    author.password: admin
    publish.url: http://localhost:4506
    publish.ip: http://127.0.0.1:4506
    login.token.name: login-token